apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/breburdaTom/homelab-argocd-app-config.git 
    targetRevision: HEAD
    path: Charts/nextcloud
  destination: 
    server: https://kubernetes.default.svc
    namespace: nextcloud

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
